a = input('digite literalmente qualquer coisa: ')
print('O tipo primitivo dessa variavel é: ', type(a))
print('só tem espaços?', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('é todo em maiusculo?', a.isupper())
print('é todo minusculo?', a.islower())
print('é capitalizada?', a.istitle())
